# Generated by Django 3.2.3 on 2021-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angles',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plunger',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spring',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variables',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
