# Generated by Django 3.1.6 on 2021-06-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angles',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angles', to='force.project'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='force.project'),
        ),
        migrations.AlterField(
            model_name='plunger',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plungers', to='force.project'),
        ),
        migrations.AlterField(
            model_name='spring',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='springs', to='force.project'),
        ),
        migrations.AlterField(
            model_name='variables',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='force.project'),
        ),
    ]
