# Generated by Django 3.2.3 on 2021-07-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='agree',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
