# Generated by Django 3.2.3 on 2021-07-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angles',
            name='FN',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='angles',
            name='plungerFric',
            field=models.BooleanField(),
        ),
    ]
