# Generated by Django 3.1.6 on 2021-06-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0002_auto_20210617_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angles',
            old_name='angles_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='plunger',
            old_name='plunger_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='spring',
            old_name='spring_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='variables',
            old_name='variables_key',
            new_name='key',
        ),
    ]
