# Generated by Django 3.1.6 on 2021-07-23 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0003_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='emails_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
