# Generated by Django 3.1.6 on 2021-07-29 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0004_auto_20210723_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='user',
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
