# Generated by Django 3.1.6 on 2021-07-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0005_auto_20210729_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='force.mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
