# Generated by Django 3.1.6 on 2021-07-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0006_flags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flags',
            new_name='Flag',
        ),
    ]
