# Generated by Django 3.1.6 on 2021-08-26 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0009_rename_datetime_project_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_flags', to='force.mail'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
