# Generated by Django 3.2.3 on 2021-09-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0010_auto_20210826_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angles',
            old_name='key',
            new_name='angles_key',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='key',
            new_name='contact_key',
        ),
        migrations.RenameField(
            model_name='plunger',
            old_name='key',
            new_name='plunger_key',
        ),
        migrations.RenameField(
            model_name='spring',
            old_name='key',
            new_name='spring_key',
        ),
        migrations.RenameField(
            model_name='variables',
            old_name='key',
            new_name='variables_key',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='agree',
        ),
    ]
