# Generated by Django 3.2.3 on 2021-09-27 19:52

from django.db import migrations, models
import force.models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0014_auto_20210926_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angles',
            name='angles_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='angles',
            name='plungerFric',
            field=models.FloatField(validators=[force.models.plungerFric_validation]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mu',
            field=models.FloatField(validators=[force.models.validate_fractional, force.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='plunger',
            name='f',
            field=models.FloatField(validators=[force.models.validate_fractional, force.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='plunger',
            name='plunger_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='assembly_number',
            field=models.CharField(max_length=8, validators=[force.models.validate_assembly_number]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(help_text='The first symbol should be a capital latin letter and next five - digits', max_length=6, unique=True, validators=[force.models.validate_project_number]),
        ),
        migrations.AlterField(
            model_name='spring',
            name='spring_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variables',
            name='variables_key',
            field=models.CharField(max_length=255),
        ),
    ]
