# Generated by Django 3.2.7 on 2021-09-30 20:03

from django.db import migrations, models
import force.models


class Migration(migrations.Migration):

    dependencies = [
        ('force', '0016_alter_project_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mu',
            field=models.FloatField(validators=[force.models.validate_fractional]),
        ),
        migrations.AlterField(
            model_name='plunger',
            name='f',
            field=models.FloatField(validators=[force.models.validate_fractional]),
        ),
        migrations.DeleteModel(
            name='Variables',
        ),
    ]
